In [9]:
import pandas
internationaltourism = pandas.read_csv('Downloads/InternationalTourismExpenditures.csv')
internationaltourism

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.640000e+08,2.610000e+08,2.870000e+08,2.940000e+08,3.420000e+08,3.520000e+08,3.610000e+08,3.320000e+08,3.620000e+08,NaN
1,Afghanistan,AFG,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.000000e+07,1.060000e+08,2.550000e+08,1.100000e+08,1.380000e+08,1.400000e+08,1.510000e+08,8.900000e+07,1.320000e+08,NaN
2,Angola,AGO,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.700000e+08,2.750000e+08,3.230000e+08,2.880000e+08,3.160000e+08,5.050000e+08,3.890000e+08,8.230000e+08,1.216000e+09,NaN
3,Albania,ALB,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.691000e+09,1.452000e+09,1.676000e+09,1.374000e+09,1.567000e+09,1.689000e+09,1.310000e+09,1.338000e+09,1.472000e+09,NaN
4,Andorra,AND,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,ARB,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.011045e+10,6.542197e+10,6.944852e+10,7.625694e+10,8.088452e+10,9.079694e+10,8.687171e+10,8.838847e+10,8.909326e+10,NaN
6,United Arab Emirates,ARE,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.034700e+10,1.181800e+10,1.320600e+10,1.507200e+10,1.618800e+10,1.584800e+10,1.663700e+10,1.712700e+10,1.764500e+10,NaN
7,Argentina,ARG,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.808000e+09,6.448000e+09,7.602000e+09,8.466000e+09,8.421000e+09,7.837000e+09,9.348000e+09,1.172900e+10,1.351600e+10,NaN
8,Armenia,ARM,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.960000e+08,6.410000e+08,7.560000e+08,8.740000e+08,1.007000e+09,1.101000e+09,1.057000e+09,1.119000e+09,1.325000e+09,NaN
9,American Samoa,ASM,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,ATG,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.400000e+07,5.100000e+07,4.900000e+07,4.900000e+07,5.000000e+07,8.900000e+07,9.500000e+07,1.010000e+08,1.060000e+08,NaN
11,Australia,AUS,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.268000e+10,2.785100e+10,3.396700e+10,3.522600e+10,3.519700e+10,3.246200e+10,2.861400e+10,3.292300e+10,3.949100e+10,NaN
12,Austria,AUT,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.081700e+10,1.012200e+10,1.054800e+10,9.991000e+09,1.025400e+10,1.109100e+10,1.133500e+10,1.163200e+10,1.287800e+10,NaN
13,Azerbaijan,AZE,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.880000e+08,8.560000e+08,1.778000e+09,2.617000e+09,3.032000e+09,3.163000e+09,2.743000e+09,2.593000e+09,2.803000e+09,NaN
14,Burundi,BDI,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.100000e+07,3.500000e+07,4.900000e+07,2.500000e+07,3.400000e+07,3.800000e+07,2.900000e+07,2.800000e+07,2.400000e+07,NaN
15,Belgium,BEL,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.904500e+10,1.886600e+10,2.065800e+10,2.236700e+10,2.451100e+10,2.643500e+10,2.112300e+10,2.151900e+10,2.299500e+10,NaN
16,Benin,BEN,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.800000e+07,9.100000e+07,8.100000e+07,9.600000e+07,3.950000e+07,5.420000e+07,1.410000e+08,8.700000e+07,NaN,NaN
17,Burkina Faso,BFA,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.110000e+08,1.100000e+08,1.290000e+08,1.460000e+08,2.150000e+08,1.760000e+08,1.600000e+08,1.760000e+08,NaN,NaN
18,Bangladesh,BGD,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.510000e+08,8.350000e+08,8.190000e+08,8.890000e+08,1.308000e+09,7.820000e+08,8.270000e+08,8.430000e+08,1.118000e+09,NaN
19,Bulgaria,BGR,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.955000e+09,9.750000e+08,1.063000e+09,1.096000e+09,1.342000e+09,1.459000e+09,1.346000e+09,1.636000e+09,2.047000e+09,NaN
20,Bahrain,BHR,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.970000e+08,6.840000e+08,8.990000e+08,9.750000e+08,1.001000e+09,7.580000e+08,9.420000e+08,1.921000e+09,1.823000e+09,NaN
21,"Bahamas, The",BHS,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.860000e+08,3.690000e+08,3.470000e+08,3.840000e+08,3.620000e+08,3.280000e+08,3.480000e+08,4.400000e+08,5.540000e+08,NaN
22,Bosnia and Herzegovina,BIH,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.850000e+08,2.470000e+08,2.140000e+08,1.960000e+08,1.980000e+08,2.050000e+08,1.950000e+08,2.060000e+08,2.570000e+08,NaN
23,Belarus,BLR,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.520000e+08,7.480000e+08,7.290000e+08,9.480000e+08,1.333000e+09,1.308000e+09,9.970000e+08,8.910000e+08,1.082000e+09,NaN
24,Belize,BLZ,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.300000e+07,3.900000e+07,3.700000e+07,3.900000e+07,4.200000e+07,5.100000e+07,5.000000e+07,5.500000e+07,5.300000e+07,NaN
25,Bermuda,BMU,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.070000e+08,4.170000e+08,3.260000e+08,3.270000e+08,3.220000e+08,3.780000e+08,3.630000e+08,3.730000e+08,3.690000e+08,NaN
26,Bolivia,BOL,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.880000e+08,4.210000e+08,4.100000e+08,5.020000e+08,6.600000e+08,9.530000e+08,8.490000e+08,9.600000e+08,1.017000e+09,NaN
27,Brazil,BRA,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.289700e+10,1.888300e+10,2.460800e+10,2.600800e+10,2.928600e+10,2.999800e+10,2.035600e+10,1.706800e+10,2.299100e+10,NaN
28,Barbados,BRB,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.930000e+08,3.510000e+08,1.240000e+08,8.400000e+07,7.800000e+07,NaN,NaN,NaN,NaN,NaN
29,Brunei Darussalam,BRN,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.770000e+08,NaN,NaN,5.910000e+08,6.240000e+08,6.160000e+08,4.590000e+08,4.990000e+08,5.040000e+08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.240300e+10,5.077900e+10,6.084710e+10,6.667970e+10,7.346010e+10,7.468300e+10,6.601300e+10,6.546700e+10,7.583998e+10,NaN
235,Timor-Leste,TLS,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.900000e+07,6.800000e+07,6.200000e+07,9.200000e+07,5.700000e+07,8.400000e+07,1.000000e+08,1.180000e+08,1.370000e+08,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.451750e+10,2.880550e+10,2.748758e+10,2.591256e+10,2.825196e+10,2.982707e+10,2.970645e+10,3.061437e+10,NaN,NaN
237,Tonga,TON,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.980000e+07,2.160000e+07,2.340000e+07,2.850000e+07,2.910000e+07,3.010000e+07,3.240000e+07,2.380000e+07,3.770000e+07,NaN
238,South Asia (IDA & IBRD),TSA,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.268200e+10,1.445200e+10,1.826500e+10,1.901400e+10,1.969300e+10,2.354100e+10,2.448000e+10,2.640600e+10,3.005300e+10,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.291661e+10,2.700623e+10,2.973148e+10,2.755363e+10,2.693767e+10,2.761796e+10,2.804533e+10,2.204834e+10,2.740513e+10,NaN
240,Trinidad and Tobago,TTO,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.360000e+08,9.700000e+07,1.880000e+08,2.230000e+08,1.160000e+08,1.680000e+08,2.530000e+08,2.300000e+08,1.470000e+08,NaN
241,Tunisia,TUN,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.780000e+08,6.110000e+08,6.780000e+08,6.730000e+08,7.680000e+08,7.700000e+08,7.670000e+08,8.230000e+08,8.710000e+08,NaN
242,Turkey,TUR,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.061000e+09,5.817000e+09,5.372000e+09,4.585000e+09,5.253000e+09,5.475000e+09,5.683000e+09,5.025000e+09,5.181000e+09,NaN
243,Tuvalu,TUV,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.500000e+06,8.700000e+06,1.145000e+07,1.150000e+07,7.550000e+06,NaN,NaN,NaN,NaN,NaN
244,Tanzania,TZA,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.060000e+08,8.610000e+08,9.280000e+08,1.003000e+09,1.101000e+09,1.206000e+09,1.329000e+09,1.009000e+09,8.990000e+08,NaN
245,Uganda,UGA,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.510000e+08,4.640000e+08,5.400000e+08,6.420000e+08,3.490000e+08,3.420000e+08,2.780000e+08,2.900000e+08,3.110000e+08,NaN
246,Ukraine,UKR,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.751000e+09,4.134000e+09,4.829000e+09,5.536000e+09,6.300000e+09,5.470000e+09,5.408000e+09,6.306000e+09,7.543000e+09,NaN
247,Upper middle income,UMC,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.619400e+11,1.962130e+11,2.347870e+11,2.807610e+11,3.296840e+11,4.289560e+11,4.232510e+11,4.127960e+11,4.452990e+11,NaN
248,Uruguay,URY,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.420000e+08,5.490000e+08,7.970000e+08,1.043000e+09,1.504000e+09,1.604000e+09,1.388000e+09,1.139000e+09,1.356000e+09,NaN
249,United States,USA,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.029530e+11,1.100490e+11,1.164480e+11,1.299020e+11,1.301480e+11,1.405580e+11,1.500440e+11,1.609370e+11,1.739190e+11,NaN
250,Uzbekistan,UZB,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251,St. Vincent and the Grenadines,VCT,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.400000e+07,1.500000e+07,1.310000e+07,1.370000e+07,1.410000e+07,3.000000e+07,3.500000e+07,3.400000e+07,3.400000e+07,NaN
252,"Venezuela, RB",VEN,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.019000e+09,2.944000e+09,3.994000e+09,4.592000e+09,5.417000e+09,4.118000e+09,3.249000e+09,2.920000e+09,NaN,NaN
253,British Virgin Islands,VGB,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,Vietnam,VNM,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.100000e+09,1.470000e+09,1.710000e+09,1.856000e+09,2.050000e+09,2.650000e+09,3.595000e+09,4.500000e+09,5.040000e+09,NaN
256,Vanuatu,VUT,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.800000e+07,3.400000e+07,3.900000e+07,4.300000e+07,4.600000e+07,4.100000e+07,3.400000e+07,NaN,NaN,NaN
257,World,WLD,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.235370e+11,1.004990e+12,1.117840e+12,1.184400e+12,1.264410e+12,1.411750e+12,1.352430e+12,1.366100e+12,1.449150e+12,NaN
258,Samoa,WSM,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000e+07,2.520000e+07,2.220000e+07,2.230000e+07,1.390000e+07,4.100000e+06,2.900000e+06,2.100000e+06,3.500000e+06,NaN
259,Kosovo,XKX,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.770000e+08,2.520000e+08,2.580000e+08,1.480000e+08,1.610000e+08,1.580000e+08,7.900000e+07,5.600000e+07,NaN,NaN
261,South Africa,ZAF,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.421000e+09,8.139000e+09,8.397000e+09,7.145000e+09,6.491000e+09,6.314000e+09,5.735000e+09,5.354000e+09,6.064000e+09,NaN
262,Zambia,ZMB,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.430000e+08,1.670000e+08,2.230000e+08,3.030000e+08,3.570000e+08,3.780000e+08,4.000000e+08,4.230000e+08,4.100000e+08,NaN
263,Zimbabwe,ZWE,"International tourism, expenditures (current US$)",ST.INT.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.670000e+08,2.030000e+08,3.170000e+08,3.870000e+08,4.410000e+08,4.510000e+08,5.570000e+08,4.060000e+08,3.380000e+08,NaN